version: '3'
services:
  cloneinsta:
    container_name: clone_insta.pv
    image:  pagevamp/nginx-php7-fpm:php74
    restart: always
    environment:
      - VIRTUAL_HOST=clone_insta.pv
    volumes:
      - ./:/var/www
      - ./docker/sites/default.conf:/etc/nginx/sites-enabled/default
    networks:
      - pagevamp

networks:
  pagevamp:
    external: true
